### ISSUE TITLE
Fix IOError with directories that appears only in process-one

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#101]
Seeing this oddness when running `jp-fukushima` under `TestOA.test_single_jp_f()`, though this source does complete as a whole when run under process-all:

    Traceback (most recent call last):
      File "/Users/migurski/Sites/OpenAddresses-Machine/openaddr/__init__.py", line 162, in conform
        csv_path, addr_count = task4.convert(data, decompressed_paths, workdir)
      File "/Users/migurski/Sites/OpenAddresses-Machine/openaddr/conform.py", line 361, in convert
        rc = conform_cli(source_definition, source_path, dest_path)
      File "/Users/migurski/Sites/OpenAddresses-Machine/openaddr/conform.py", line 765, in conform_cli
        extract_to_source_csv(source_definition, source_path, extract_path)
      File "/Users/migurski/Sites/OpenAddresses-Machine/openaddr/conform.py", line 712, in extract_to_source_csv
        csv_source_to_csv(source_definition, source_path, extract_path)
      File "/Users/migurski/Sites/OpenAddresses-Machine/openaddr/conform.py", line 474, in csv_source_to_csv
        with csvopen(source_path, 'r', encoding=enc) as source_fp:
      File "/Users/migurski/Sites/OpenAddresses-Machine/openaddr/compat.py", line 53, in csvopen
        return io.FileIO(filename, mode=mode)
    IOError: [Errno 21] Is a directory: '/var/folders/_0/1_xvzf1d7617_1qnntjkb1zm0000gn/T/testOA-zmr0Bc/process_one-7kVFkM/conform-pE2_mQ/unzipped/07000-12.0a'

**Comment by migurski** [comment]
Can’t replicate this issue, under Mac or Linux and Python 2 or 3.
