### ISSUE TITLE
Handle job/file repetition gracefully in ci.worker

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#121]
Workers don’t like running multiple things at a time, and should generate new directory names using `mkdtemp()` instead of job ID or event file ID:

```
2015-06-15 22:19:12,529   ERROR: Error in worker main()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/worker.py", line 94, in main
    pop_task_from_taskqueue(task_Q, done_Q, due_Q, _web_output_dir)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/__init__.py", line 432, in pop_task_from_taskqueue
    result = worker.do_work(task.data['id'], task.data['content'], output_dir)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/worker.py", line 31, in do_work
    os.mkdir(out_dir)
```

**Comment by migurski** [comment]
Done in 8cd99a3.
