### ISSUE TITLE
Issues when running machine

### ISSUE THREAD

**Issue by MiniCodeMonkey** [openaddresses/machine#21]
Hey,

I know machine is a work on progress. But still wanted to flag a few issues I had, running `openaddr-process`

```
$ openaddr-process -a MY_KEY -s MY_SECRET -l log.txt MY_BUCKETNAME
Traceback (most recent call last):
  File "/usr/local/bin/openaddr-process", line 9, in <module>
    load_entry_point('OpenAddresses-Machine==1.1.1', 'console_scripts', 'openaddr-process')()
  File "/usr/local/lib/python2.7/dist-packages/openaddr/process.py", line 39, in main
    process(s3, paths.sources, run_name)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/process.py", line 98, in process
    source_extras1 = read_state(s3, sourcedir)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/process.py", line 69, in read_state
    state_key = s3.get_key('state.txt')
  File "/usr/local/lib/python2.7/dist-packages/openaddr/__init__.py", line 87, in get_key
    self._bucket = connect_s3(key, secret).get_bucket(bucketname)
NameError: global name 'key' is not defined
```

It's been years since I worked with Python, so correct me if I'm wrong. But it looks like line 87-95 needs to be changed to reference the class scope instead of the local scope, in addition `bucketname` needs to be changed to `bucket`.
```python
    def get_key(self, name):
        if not self._bucket:
            self._bucket = connect_s3(self._key, self._secret).get_bucket(name)
        return self._bucket.get_key(name)

    def new_key(self, name):
        if not self._bucket:
            self._bucket = connect_s3(self._key, self._secret).get_bucket(name)
        return self._bucket.new_key(name)
```

After changing these lines, I can run process but I do however see failures on all sources that needs to be downloaded via FTP, just like this:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/__init__.py", line 153, in thread_work
    downloaded_files = task.download(source_urls, workdir)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/cache.py", line 129, in download
    raise DownloadError("Could not connect to URL", e)
DownloadError: ('Could not connect to URL', InvalidSchema(u"No connection adapters were found for 'ftp://anonymous:anonymous@ftp.gis.mt.gov/CadastralFramework/Pondera/PonderaOwnerParcel_shp.zip'",))
   Thread-7    817606.5   INFO: /var/opt/openaddresses/sources/us-ia-winneshiek.json
```

It looks like the `request` class used for this doesn't seem to support FTP? It does however look like FTP sources are processed correctly on http://data.openaddresses.io/runs/1417451418.786/

I've tried using both the `master` branch and `ditch-node` branch. But seems to have the same issues.

Mathias

**Comment by migurski** [comment]
Closing this ticket since it seems to be working for you.
