### ISSUE TITLE
Virginia not generating a sample

### ISSUE THREAD

**Issue by waldoj** [openaddresses/machine#244]
Here's [the output](http://data.openaddresses.io.s3.amazonaws.com/runs/28535/output.txt):

```
2015-10-21 18:01:01,260    DEBUG: URL says ".zip" for https://ftp.vgingis.com/Download/VA_SiteAddress.txt.zip
2015-10-21 18:01:01,261    DEBUG: Guessed user_input-2e381f67.zip for https://ftp.vgingis.com/Download/VA_SiteAddress.txt.zip
2015-10-21 18:01:01,261    DEBUG: Requesting https://ftp.vgingis.com/Download/VA_SiteAddress.txt.zip with args None
2015-10-21 18:03:12,766     INFO: Downloaded 173074425 bytes for file /tmp/worker-eB9rim/work-LicM0Y/out/process_one-rOZ5c3/cache-lNaMCv/http/user_input-2e381f67.zip
2015-10-21 18:03:13,442     INFO: Cached data in file:///tmp/worker-eB9rim/work-LicM0Y/out/process_one-rOZ5c3/cached/user_input-2e381f67.zip
2015-10-21 18:03:13,644    DEBUG: URL says ".zip" for file:///tmp/worker-eB9rim/work-LicM0Y/out/process_one-rOZ5c3/cached/user_input-2e381f67.zip
2015-10-21 18:03:13,644    DEBUG: Guessed user_input-d384c3a2.zip for file:///tmp/worker-eB9rim/work-LicM0Y/out/process_one-rOZ5c3/cached/user_input-2e381f67.zip
2015-10-21 18:03:14,999    DEBUG: File exists /tmp/worker-eB9rim/work-LicM0Y/out/process_one-rOZ5c3/conform-5kAtCV/http/user_input-d384c3a2.zip
2015-10-21 18:03:14,999     INFO: Downloaded to [u'/tmp/worker-eB9rim/work-LicM0Y/out/process_one-rOZ5c3/conform-5kAtCV/http/user_input-d384c3a2.zip']
2015-10-21 18:03:30,029    DEBUG: Expanded file /tmp/worker-eB9rim/work-LicM0Y/out/process_one-rOZ5c3/conform-5kAtCV/unzipped/VA_SiteAddress.txt
2015-10-21 18:03:30,030    DEBUG: Skipped file VA_SiteAddress.txt.xml
2015-10-21 18:03:30,030     INFO: Decompressed to 1 files
2015-10-21 18:03:30,030  WARNING: Error doing excerpt; skipping
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openaddr/__init__.py", line 161, in conform
    _L.info("Sampled %d records", len(data_sample))
TypeError: object of type 'NoneType' has no len()
2015-10-21 18:03:30,030    DEBUG: Converting to /tmp/worker-eB9rim/work-LicM0Y/out/process_one-rOZ5c3/conform-5kAtCV
2015-10-21 18:03:30,031    DEBUG: extract temp file /tmp/openaddr-extracted-A0zL6m.csv
2015-10-21 18:03:30,031     INFO: Converting source CSV /tmp/worker-eB9rim/work-LicM0Y/out/process_one-rOZ5c3/conform-5kAtCV/unzipped/VA_SiteAddress.txt
2015-10-21 20:30:30,005     INFO: Converted to /tmp/worker-eB9rim/work-LicM0Y/out/process_one-rOZ5c3/conform-5kAtCV/converted/VA_SiteAddress.csv with 3654477 addresses
2015-10-21 20:30:30,128     INFO: Processed data in /tmp/worker-eB9rim/work-LicM0Y/out/process_one-rOZ5c3/out.csv
```

**Comment by slibby** [comment]
@waldoj looks like ".txt" needs to be added here: https://github.com/openaddresses/machine/blob/614941bc3acb01b12ff4c92d46c3afd103c724da/openaddr/conform.py#L147

**Comment by waldoj** [comment]
Woo, I feel like I'm doing something! ;)

**Comment by migurski** [comment]
Still seeing the same error after the addition of `.txt`.

```
 16554    559922.6 WARNING: Error doing excerpt; skipping
Traceback (most recent call last):
  File "openaddr/__init__.py", line 160, in conform
    data_sample, geometry_type = task3.excerpt(decompressed_paths, workdir, conform)
  File "openaddr/conform.py", line 222, in excerpt
    layer = datasource.GetLayer()
AttributeError: 'NoneType' object has no attribute 'GetLayer'
```

Digging further.

**Comment by waldoj** [comment]
D'oh. A little follow-up on my part would have been good.

**Comment by migurski** [comment]
Looks like OGR won’t accept files with unrecognized file extensions even if it’s told to use a certain driver, so I’ve modified the conform code to append a `.csv` extension to `.txt` files.
