### ISSUE TITLE
UnicodeEncodeError for CZ

### ISSUE THREAD

**Issue by geobrando** [openaddresses/machine#246]
[cz/countrywide](https://github.com/openaddresses/openaddresses/blob/c583882048336827360f4b6674a325ec5f8f5f33/sources/cz/countrywide.json)

```
2015-10-24 01:03:40,340  WARNING: Error in process_one.process()
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openaddr/process_one.py", line 62, in process
    conform_result = conform(temp_src, temp_dir, cache_result.todict())
  File "/usr/local/lib/python2.7/dist-packages/openaddr/__init__.py", line 187, in conform
    conform_license(data.get('license')),
  File "/usr/local/lib/python2.7/dist-packages/openaddr/conform.py", line 889, in conform_license
    return str(license)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa7' in position 0: ordinal not in range(128)
```

**Comment by migurski** [comment]
I’m testing this to determine if it happens every time.

**Comment by migurski** [comment]
:-1: Python 2.x unicode.

**Comment by NelsonMinar** [comment]
Is there any reason to maintain Python 2.x compatibility?

**Comment by migurski** [comment]
We still have a couple things that run on OSM US, where I'm not confident messing with packages. I think it's Ubuntu 12 LTS. Generally inertia though.
