### ISSUE TITLE
Unicode Error during collection process

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#320]
Maybe a problem with `fi/päijät-häme-fi.json`?

```
2016-05-02 05:00:39,885    INFO: Adding fi/lappi-sv to /tmp/collected-ZAJGfW/openaddr-collected-europe.zip
2016-05-02 05:00:39,885    INFO: Skipping street name expansion for fi/lappi-sv (not U.S.)
2016-05-02 05:00:43,400    INFO: Adding fi/lappi-sv to /tmp/collected-ZAJGfW/openaddr-collected-global.zip
2016-05-02 05:00:43,401    INFO: Skipping street name expansion for fi/lappi-sv (not U.S.)
2016-05-02 05:00:47,008    INFO: Adding fi/päijät-häme-fi to /tmp/collected-ZAJGfW/openaddr-collected-europe.zip
2016-05-02 05:00:47,008    INFO: Skipping street name expansion for fi/päijät-häme-fi (not U.S.)
2016-05-02 05:00:49,512   ERROR: 'ascii' codec can't encode character u'\xe4' in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/__init__.py", line 932, in decorated_function
    return route_function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/collect.py", line 91, in main
    collection.collect(result)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/collect.py", line 155, in collect
    add_source_to_zipfile(self.zip, result)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/collect.py", line 306, in add_source_to_zipfile
    expand_and_add_csv_to_zipfile(zip_out, zipinfo.filename, zipped_file, do_expand)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/collect.py", line 230, in expand_and_add_csv_to_zipfile
    _add_spatial_summary_to_zipfile(zip_out, arc_filename, size, squares)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/ci/collect.py", line 260, in _add_spatial_summary_to_zipfile
    vrt_content = file.read().format(**args)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 1: ordinal not in range(128)
```

**Comment by migurski** [comment]
Supposedly fixed, but I don’t understand why diacritics in Mexico filenames were not triggering the behavior?

**Comment by migurski** [comment]
Probably because the diacritics were in MX directory names, but the filenames were all plain ASCII "statewide.csv".
