### ISSUE TITLE
Error in dequeue RunState 

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#425]
```
2016-11-05 17:39:24,426   ERROR: Error in dequeue main()
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/openaddr/ci/run_dequeue.py", line 33, in main
    pop_task_from_donequeue(done_Q, config['GITHUB_AUTH'])
  File "/usr/local/lib/python3.4/dist-packages/openaddr/ci/__init__.py", line 939, in pop_task_from_donequeue
  File "/usr/local/lib/python3.4/dist-packages/openaddr/ci/objects.py", line 107, in __init__
    unexpected = ', '.join(set(self.keys) - set(RunState.key_attrs.keys()))
AssertionError: RunState should not have keys preview
```

**Comment by migurski** [comment]
Nevermind, just neglected to update the dequeue process with matching new code.
