### ISSUE TITLE
encoding problem writing samples

### ISSUE THREAD

**Issue by NelsonMinar** [openaddresses/machine#46]
@migurski I think this one is for you. A lot of Japanese and Korean sources are failing the same way, trying to write Unicode in `process_one()` and failing. For example `kr-seoul-chunggu-old` or `jp-okinawa`.

````
I process_:43   Processed data in /mnt/sdc1/geodata/oa2/out/process_one-DojCAp/out.csv
E process_:129  'utf8' codec can't decode byte 0x93 in position 0: invalid start byte
Traceback (most recent call last):
  File "/home/nelson/src/oa/openaddresses-machine/openaddr/process_one.py", line 127, in main
    file_path = process(args.source, args.destination)
  File "/home/nelson/src/oa/openaddresses-machine/openaddr/process_one.py", line 48, in process
    state_path = write_state(source, destination, cache_result, conform_result, temp_dir)
  File "/home/nelson/src/oa/openaddresses-machine/openaddr/process_one.py", line 76, in write_state
    json.dump(conform_result.sample, sample_file, indent=2)
  File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
    for chunk in iterable:
  File "/usr/lib/python2.7/json/encoder.py", line 431, in _iterencode
    for chunk in _iterencode_list(o, _current_indent_level):
  File "/usr/lib/python2.7/json/encoder.py", line 332, in _iterencode_list
    for chunk in chunks:
  File "/usr/lib/python2.7/json/encoder.py", line 313, in _iterencode_list
    yield buf + _encoder(value)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x93 in position 0: invalid start byte
````

**Comment by NelsonMinar** [comment]
Derp, this is a duplicate of #35. Sorry.
