### ISSUE TITLE
Categorize failures meaningfully

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#460]
Talked with @iandees about this a few weeks ago: it would be useful to parse the log files for failed sources so that we could categorize them into meaningful buckets. Examples include sources whose data now 404s, sources that require a token to be generated, sources that haven't changed and are stale, etc.

**Comment by migurski** [comment]
```
2016-11-27 15:47:37,433  WARNING: Error in process_one.process()
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/openaddr/process_one.py", line 56, in process
    cache_result = cache(temp_src, temp_dir, extras)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/__init__.py", line 109, in cache
    downloaded_files = task.download(source_urls, workdir, data.get('conform'))
  File "/usr/local/lib/python3.4/dist-packages/openaddr/cache.py", line 352, in download
    metadata = downloader.get_metadata()
  File "/usr/local/lib/python3.4/dist-packages/esridump/dumper.py", line 108, in get_metadata
    metadata_json = self._handle_esri_errors(response, "Could not retrieve layer metadata")
  File "/usr/local/lib/python3.4/dist-packages/esridump/dumper.py", line 72, in _handle_esri_errors
    ', '.join(error['details']),
esridump.errors.EsriDownloadError: Could not retrieve layer metadata: Token Required 
```

— http://s3.amazonaws.com/data.openaddresses.io/runs/131001/output.txt from http://results.openaddresses.io/sources/us/tx/runnels

**Comment by migurski** [comment]
The [Docker approach](https://github.com/openaddresses/openaddresses/blob/master/scripts/us/tn/) to ESRI tokens is not going to be sustainable. @iandees, what should we do with these? It seems clear that they’ll need to be periodically re-cached manually from a web browser.

**Comment by migurski** [comment]
Another thing to categorize: stale-looking data based on no changes for 6, 9, or 12 months.

**Comment by iandees** [comment]
I've just been running `esri2geojson` (from pyesridump) directly and uploading the resulting GeoJSON.
