### ISSUE TITLE
Investigate dotmap failure

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#526]
Just saw a memory error:

```
2017-01-21 11:48:38,701   DEBUG: Opening /tmp/processed-g6q6yj7k.zip (br/sp/statewide)
Traceback (most recent call last):
  File "/usr/local/bin/openaddr-update-dotmap", line 9, in <module>
    load_entry_point('OpenAddresses-Machine==4.0.4', 'console_scripts', 'openaddr-update-dotmap')()
  File "/usr/local/lib/python3.4/dist-packages/openaddr/dotmap.py", line 177, in main
    for feature in stream_all_features(results):
  File "/usr/local/lib/python3.4/dist-packages/openaddr/dotmap.py", line 202, in stream_all_features
    buffer = csvIO(bytes.decode('utf8'))
MemoryError
```

There’s probably a way to stream this data instead of decoding it all at once, and it might be easier if all Python 2 support is removed first (https://github.com/openaddresses/machine/issues/527).

**Comment by migurski** [comment]
Just saw this error again, at the same starting source.
