### ISSUE TITLE
Investigate failure when using regexp function for lat/lon

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#534]
Observed in https://github.com/openaddresses/openaddresses/pull/2426: 

```
2017-01-24 23:15:14,852  WARNING: Error doing conform; skipping
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/openaddr/__init__.py", line 182, in conform
    csv_path, addr_count = task4.convert(data, decompressed_paths, workdir)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/conform.py", line 542, in convert
    rc = conform_cli(source_definition, source_path, dest_path)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/conform.py", line 1187, in conform_cli
    extract_to_source_csv(source_definition, source_path, extract_path)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/conform.py", line 1136, in extract_to_source_csv
    csv_source_to_csv(source_definition, source_path, extract_path)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/conform.py", line 748, in csv_source_to_csv
    old_latlon.extend([s.upper() for s in old_latlon])
  File "/usr/local/lib/python3.4/dist-packages/openaddr/conform.py", line 748, in <listcomp>
    old_latlon.extend([s.upper() for s in old_latlon])
AttributeError: 'dict' object has no attribute 'upper'
```

**Comment by andrewharvey** [comment]
Looking through the code, it seems the reprojection of lon,lat happens before any of the attribute functions run, which indicates attribute functions aren't supported in the `lat` or `lon` fields.

It seems the fix would require the attribute functions to be run first before any of the reprojection occurs.

I ran into this issue with https://github.com/openaddresses/openaddresses/pull/3926/commits/ff8d1bb06aaa60a9554c5b7021901e6210312a1c at https://s3.amazonaws.com/data.openaddresses.io/runs/380939/output.txt when doing

```json
        "lon": {
            "function": "regexp",
            "field": "EASTING",
            "pattern": "^([^|]*)"
        },
        "lat": {
            "function": "regexp",
            "field": "NORTHING",
            "pattern": "^([^|]*)"
        }
```

**Comment by andrewharvey** [comment]
when this lands https://github.com/openaddresses/openaddresses/pull/3927 can be reverted
