### ISSUE TITLE
Investigate new dotmap failure

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#542]
After fixing #526, now the volume has insufficient temp space:

```
Reordering geometry: 10% 
Reordering geometry: 11% 
Reordering geometry: 12% 
Reordering geometry: 13% 
Reordering geometry: 14% 
index: Write to temporary file failed: No space left on device
2017-02-07 08:56:43,991    INFO: Uploading oa-je7608gs.mbtiles to Mapbox open-addresses's open-addresses.lec54np1
2017-02-07 08:56:43,991   DEBUG: GET /uploads/v1/open-addresses/credentials
2017-02-07 08:56:44,420   DEBUG: /tmp/oa-je7608gs.mbtiles --> 55/_pending/08kbaotfpmw2v100p6ilavyic/open-addresses
2017-02-07 08:56:44,531   DEBUG: POST /uploads/v1/open-addresses '{"tileset": "open-addresses.lec54np1", "url": "https://tilestream-tilesets-production.s3.amazonaws.com/55/_pending/08kbaotfpmw2v100p6ilavyic/open-addresses"}'
2017-02-07 08:56:45,613   DEBUG: GET /uploads/v1/open-addresses/ciyvaliz0001b33oeudjkfwje
2017-02-07 08:57:16,140   DEBUG: GET /uploads/v1/open-addresses/ciyvaliz0001b33oeudjkfwje
Traceback (most recent call last):
  File "/usr/local/bin/openaddr-update-dotmap", line 9, in <module>
    load_entry_point('OpenAddresses-Machine==4.1.5', 'console_scripts', 'openaddr-update-dotmap')()
  File "/usr/local/lib/python3.4/dist-packages/openaddr/dotmap.py", line 182, in main
    mapbox_upload(mbtiles_filename, args.tileset_id, args.mapbox_user, args.mapbox_key)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/dotmap.py", line 62, in mapbox_upload
    _mapbox_create_upload(url, tileset, username, api_key)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/dotmap.py", line 112, in _mapbox_create_upload
    return _mapbox_wait_for_upload(resp['id'], username, api_key)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/dotmap.py", line 128, in _mapbox_wait_for_upload
    raise RuntimeError(str(status['error']))
RuntimeError: Tileset is empty.
```

**Comment by migurski** [comment]
The dotmaps at https://openaddresses.io are currently up-to-date; I'm waiting for a normal cron cycle to pass in ~4 days before I declare this fixed. /cc @nvkelso.

**Comment by nvkelso** [comment]
Woot!
