### ISSUE TITLE
Machine bombs on ESRI sources with `NaN` centroid

### ISSUE THREAD

**Issue by trescube** [openaddresses/machine#543]
While running [Orange County, NY](https://github.com/openaddresses/openaddresses/pull/2291), the machine errors out if the centroid for the geometry returns `NaN,NaN`.  The error is:

```
2017-02-08 18:58:35,871  WARNING: Error in process_one.process()
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/openaddr/process_one.py", line 55, in process
    cache_result = cache(temp_src, temp_dir, extras)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/__init__.py", line 104, in cache
    downloaded_files = task.download(source_urls, workdir, data.get('conform'))
  File "/usr/local/lib/python3.4/dist-packages/openaddr/cache.py", line 400, in download
    row[X_FIELDNAME] = round(centroid.x, 7)
  File "/usr/local/lib/python3.4/dist-packages/shapely/geometry/point.py", line 56, in x
    return self.coords[0][0]
IndexError: list index out of range
```

**Comment by migurski** [comment]
“NaN” is invalid JSON, so I don’t think this is fixable with a GeoJSON source. I think this should probably be closed [and fixed in pyesridump #31](https://github.com/openaddresses/pyesridump/issues/31); what do you think?

**Comment by trescube** [comment]
This is probably pretty rare since it's likely the first time the error has occurred.  While we won't get up-to-date info unless pyesridump is run and the cache has been updated, it's better than not having the data at all.  

You don't think this is fixable on line 400 of cache.py?  Wouldn't a NaN check be feasible?

**Comment by migurski** [comment]
We might not be talking about the same thing. The `NaN` error for Orange County NY looks like this:

```
2017-02-09 02:21:49,761     INFO: Non-ESRI GeoJSON source found; converting as a stream.
2017-02-09 02:21:50,522  WARNING: Error doing conform; skipping
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/ijson/backends/python.py", line 125, in parse_value
    yield ('number', common.number(symbol))
  File "/usr/local/lib/python3.4/dist-packages/ijson/common.py", line 158, in number
    number = decimal.Decimal(str_value)
  File "/usr/lib/python3.4/decimal.py", line 595, in __new__
    "Invalid literal for Decimal: %r" % value)
  File "/usr/lib/python3.4/decimal.py", line 4050, in _raise_error
    raise error(explanation)
decimal.InvalidOperation: Invalid literal for Decimal: 'N'
```

I’d prefer to fix this by having pyesridump output valid JSON. What version of the source generated the error above, on line 400 of cache.py?

**Comment by trescube** [comment]
Oh, I see, the output you're seeing is from the pyesridump-dumped data.  Running the ESRI source itself produces a different error.  Lemme find it.

**Comment by trescube** [comment]
Here's the output from the previous run using the ESRI source:  https://s3.amazonaws.com/data.openaddresses.io/runs/154952/output.txt

**Comment by migurski** [comment]
Gotcha! Found it here: http://results.openaddresses.io/jobs/15cb4925-d8d2-4a7a-b005-3f3a7eee638c.

Would it have been run against this version of the file? https://github.com/openaddresses/openaddresses/blob/a17673819429/sources/us/ny/orange.json

**Comment by trescube** [comment]
Yep, that's it, I had switched it to a cached version of the dump to see if that made a difference.
