### ISSUE TITLE
Back off when database connections are in short supply

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#613]
We experienced exhausted database connections to the main RDS instance. It’s still unclear why there were so many of them, but it may make sense to back off more than 2 seconds in workers when an operational error occurs.

```
2017-04-22 14:51:20,303   ERROR: Error in worker main()
Traceback (most recent call last):
 File "/usr/local/lib/python3.4/dist-packages/openaddr/ci/worker.py", line 60, in main
   with db_connect(args.database_url) as conn:
 File "/usr/local/lib/python3.4/dist-packages/openaddr/ci/__init__.py", line 1121, in db_connect
   return connect(dsn)
 File "/usr/local/lib/python3.4/dist-packages/psycopg2/__init__.py", line 164, in connect
   conn = _connect(dsn, connection_factory=connection_factory, async=async)
psycopg2.OperationalError: FATAL:  remaining connection slots are reserved for non-replication superuser connections
```

**Comment by migurski** [comment]
I added [a new Cloudwatch alarm to watch for this](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#alarm:alarmFilter=ANY;name=Machine%20RDS%20High%20Connections).

**Comment by migurski** [comment]
Connections seem to leak most during the faster end-stage of a batch set. There’s probably something that could be done with the use of threads and connections in `ci.pop_task_from_taskqueue()` to help with this.

**Comment by migurski** [comment]
Confirmed that this is now fixed.
