### ISSUE TITLE
Build error though data is generated

### ISSUE THREAD

**Issue by trescube** [openaddresses/machine#650]
I was updating us/nc/alamance to a GDB source and got an error:

http://results.openaddresses.io/jobs/a86e8dd5-d413-48ac-bed5-7e3864f6e231

```
2017-06-16 16:12:33,293     INFO: Decompressed to 62 files
2017-06-16 16:12:33,315    ERROR: GDAL gave Failure 1: Error occurred in filegdbtable.cpp at line 2375
2017-06-16 16:12:33,315    ERROR: GDAL gave Failure 1: Error occurred in filegdbtable.cpp at line 2703
2017-06-16 16:12:33,315  WARNING: Error doing excerpt; skipping
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/openaddr/__init__.py", line 171, in conform
    data_sample, geometry_type = task3.excerpt(decompressed_paths, workdir, conform)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/conform.py", line 325, in excerpt
    for (feature, _) in zip(layer, range(5)):
  File "/usr/lib/python3/dist-packages/osgeo/ogr.py", line 2772, in __next__
    feature = self.GetNextFeature()
  File "/usr/lib/python3/dist-packages/osgeo/ogr.py", line 1381, in GetNextFeature
    return _ogr.Layer_GetNextFeature(self, *args)
RuntimeError
```

The data file and slippy map generated are fine though.

**Comment by migurski** [comment]
Thanks, I can’t initially tell what’s going on here.
