### ISSUE TITLE
Docker Hub image out of date

### ISSUE THREAD

**Issue by thismakessand** [openaddresses/machine#721]
It looks like the latest image in docker hub for openaddr/machine is 6.8.6 (10 months ago).  And the 'latest' tag is even older.  https://hub.docker.com/r/openaddr/machine/tags

It now fails when following the instructions for running a source locally found here:
https://github.com/openaddresses/machine/blob/master/docs/install.md#running-a-source-locally

```
docker run --volume `pwd`:/vol openaddr/machine \
  openaddr-process-one -v vol/us-ca-berkeley.json vol

     1       408.3 WARNING: Error in process_one.process()
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/openaddr/process_one.py", line 87, in process
    cache_result = cache(temp_src, temp_dir, extras)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/__init__.py", line 103, in cache
    task = DownloadTask.from_type_string(data.get('type'), source)
  File "/usr/local/lib/python3.4/dist-packages/openaddr/cache.py", line 136, in from_type_string
    if type_string.lower() == 'http':
AttributeError: 'NoneType' object has no attribute 'lower'
     1       450.3   INFO: Wrote to state: vol/us-ca-berkeley/index.json
vol/us-ca-berkeley/index.json
     1       490.8   INFO: Resource usage: { user: 0%, system: 5%, memory: 446MB, read: 4KB, written: 0KB, sent: 0KB, received: 0KB, period: 0sec, procs: 1 }
     1       491.1   INFO: process shutting down
     1       491.3  DEBUG: running all "atexit" finalizers with priority >= 0
     1       491.6  DEBUG: running the remaining "atexit" finalizers
```

I ended up building the image locally to get around it, but wanted to report the issue.
Thanks!

**Comment by migurski** [comment]
Thanks for letting us know! I removed Docker Hub from our release flow a while back, but I did not delete the remaining images stored there. Right now it’s probably best to build your own images as you’ve done.
