### ISSUE TITLE
Don’t require presence of conform.lat and conform.lon

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#91]
We made them optional, but this exception is still thrown:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openaddr/__init__.py", line 160, in conform
    csv_path, addr_count = task4.convert(data, decompressed_paths, workdir)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/conform.py", line 340, in convert
    rc = conform_cli(source_definition, source_path, dest_path)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/conform.py", line 741, in conform_cli
    extract_to_source_csv(source_definition, source_path, extract_path)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/conform.py", line 693, in extract_to_source_csv
    csv_source_to_csv(source_definition, source_path, extract_path)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/conform.py", line 486, in csv_source_to_csv
    old_latlon = [source_definition["conform"]["lat"], source_definition["conform"]["lon"]]
KeyError: 'lat'
```

**Comment by NelsonMinar** [comment]
I've verified the source runs without error, so closing the bug. That source doesn't give us very good data btw, the ESRI server isn't returning street names to the downloader. But our code processes what its giving us correctly.

**Comment by geobrando** [comment]
Hmm.  Shows this was my source but only because I just renamed it.  Looks like whomever added it used the wrong endpoint or they changed the path.  Should be http://gis.salemva.gov/ArcGIS/rest/services/ParcelDataNX/MapServer/19

I'll fix that.
