### ISSUE TITLE
Fix geometry transform exception in render

### ISSUE THREAD

**Issue by migurski** [openaddresses/machine#92]
This happens at the very end:

```
Traceback (most recent call last):
  File "/usr/local/bin/openaddr-process", line 9, in <module>
    load_entry_point('OpenAddresses-Machine==1.6.4', 'console_scripts', 'openaddr-process')()
  File "/usr/local/lib/python2.7/dist-packages/openaddr/process_all.py", line 73, in main
    render.render(paths.sources, good_sources, 960, 2, png_filename, area)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/render.py", line 268, in render
    return _render_state(sources_dir, good_sources, width, resolution, filename, area)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/render.py", line 284, in _render_state
    good_geometries, bad_geometries = load_geometries(sources_dir, good_sources, area)
  File "/usr/local/lib/python2.7/dist-packages/openaddr/render.py", line 149, in load_geometries
    geometry.Transform(project)
  File "/usr/lib/python2.7/dist-packages/osgeo/ogr.py", line 4621, in Transform
    return _ogr.Geometry_Transform(self, *args)
TypeError: in method 'Geometry_Transform', argument 2 of type 'OSRCoordinateTransformationShadow *'
```

**Comment by migurski** [comment]
Looks like GDAL on Ubuntu 14.04 doesn’t know about [ESRI:54029](http://spatialreference.org/ref/esri/54029/).

```
  File "/usr/local/lib/python2.7/dist-packages/openaddr/render.py", line 136, in load_geometries
    sref_map = osr.SpatialReference(); sref_map.ImportFromEPSG(2163 if area == USA else 54029)
  File "/usr/lib/python2.7/dist-packages/osgeo/osr.py", line 598, in ImportFromEPSG
    return _osr.SpatialReference_ImportFromEPSG(self, *args)
RuntimeError: EPSG PCS/GCS code 54029 not found in EPSG support files.  Is this a valid
EPSG coordinate system?
```
